### ISSUE TITLE
Alignment of website title text with no logo

### ISSUE THREAD

**Issue by paulhibbitts** [smartgravity/grav-theme-bones-vanilla#7]
When no logo is present the website title text is slight misaligned on desktops, and a bit more so on smaller screens. It would be great if the title text was aligned on all screen sizes when no logo image file is present.

![home bones vanilla](https://cloud.githubusercontent.com/assets/1812771/12597380/c6299ebe-c439-11e5-942d-92f1b1753369.png)

![home bones vanilla 2](https://cloud.githubusercontent.com/assets/1812771/12597385/c9ce5df2-c439-11e5-811f-b0610e3cac60.png)

Thanks for considering this request.
Paul

**Comment by benblee** [comment]
Fixed in v0.5.1 release.
